version: '2'
services:
 web:
  build: ./E-gzamin-frontend/
  command: npm start
  ports:
   - "80:3000"
 db:
  image: postgres:12.2
  environment:
   POSTGRES_USER: admin
   POSTGRES_PASSWORD: password
